AppBundle\Entity\Akorder:
    type: entity
    table: akorder
    indexes:
        product_id:
            columns:
                - product_id
        user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateOrder:
            type: datetime
            nullable: true
            column: date_order
        datePayment:
            type: datetime
            nullable: true
            column: date_payment
        status:
            type: text
            nullable: false
            length: 255
            options:
                fixed: false
        quantity:
            type: integer
            nullable: false
            options:
                unsigned: false
    manyToOne:
        user:
            targetEntity: Users
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
        product:
            targetEntity: Products
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                product_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
