AppBundle\Entity\Products:
    type: entity
    table: products
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        photo:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        priceSale:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            column: price_sale
        priceBuy:
            type: decimal
            nullable: false
            precision: 5
            scale: 2
            column: price_buy
        quantityStock:
            type: boolean
            nullable: false
            column: quantity_stock
    lifecycleCallbacks: {  }
