AppBundle\Entity\Users:
    type: entity
    table: users
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        birthdate:
            type: date
            nullable: false
            column: birthDate
        address:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        zipcode:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
        phone:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        status:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        uniqid:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
